# fish completion for goobers
function __goobers_completion_examples
    command goobers __complete examples 2>/dev/null
end

function __goobers_completion_workflows
    command goobers __complete workflows 2>/dev/null
end

function __goobers_completion_runs
    command goobers __complete runs 2>/dev/null
end

function __goobers_completion_escalations
    command goobers __complete escalations 2>/dev/null
end

complete -c goobers -e
complete -c goobers -n '__fish_use_subcommand' -f -a 'version init connect examples scaffold validate up down service dashboard run signal workflow status stats cost trace escalations completion help'
complete -c goobers -s h -l help -d 'Show help'
complete -c goobers -l version -d 'Print the version'

complete -c goobers -n '__fish_seen_subcommand_from roots; and test (count (commandline -opc)) -eq 2' -f -a 'discover decommission'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and test (count (commandline -opc)) -eq 2' -f -a 'stub-sample stub-agent-instructions'
complete -c goobers -n '__fish_seen_subcommand_from examples; and test (count (commandline -opc)) -eq 2' -f -a 'list show'
complete -c goobers -n '__fish_seen_subcommand_from examples; and __fish_seen_subcommand_from show; and test (count (commandline -opc)) -eq 3' -f -a '(__goobers_completion_examples)'
complete -c goobers -n '__fish_seen_subcommand_from scaffold; and test (count (commandline -opc)) -eq 2' -f -a 'goober workflow gaggle'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and test (count (commandline -opc)) -eq 2' -f -a 'bundle'
complete -c goobers -n '__fish_seen_subcommand_from agent-kit; and test (count (commandline -opc)) -eq 2' -f -a 'install check update'
complete -c goobers -n '__fish_seen_subcommand_from portal-extension; and test (count (commandline -opc)) -eq 2' -f -a 'install status update'
complete -c goobers -n '__fish_seen_subcommand_from config; and test (count (commandline -opc)) -eq 2' -f -a 'templates diff materialize show'
complete -c goobers -n '__fish_seen_subcommand_from speech; and test (count (commandline -opc)) -eq 2' -f -a 'preflight test'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and test (count (commandline -opc)) -eq 2' -f -a 'join status leave'
complete -c goobers -n '__fish_seen_subcommand_from service; and test (count (commandline -opc)) -eq 2' -f -a 'install uninstall stop start status task-install task-uninstall task-start task-stop task-status'
complete -c goobers -n '__fish_seen_subcommand_from run; and test (count (commandline -opc)) -eq 2' -f -k -a 'abort cancel (__goobers_completion_workflows)'
complete -c goobers -n '__fish_seen_subcommand_from run; and __fish_seen_subcommand_from abort; and test (count (commandline -opc)) -eq 3' -f -k -a '(__goobers_completion_runs)'
complete -c goobers -n '__fish_seen_subcommand_from workflow; and test (count (commandline -opc)) -eq 2' -f -a 'show'
complete -c goobers -n '__fish_seen_subcommand_from workflow; and __fish_seen_subcommand_from show; and test (count (commandline -opc)) -eq 3' -f -a '(__goobers_completion_workflows)'
complete -c goobers -n '__fish_seen_subcommand_from runs; and test (count (commandline -opc)) -eq 2' -f -a 'list du'
complete -c goobers -n '__fish_seen_subcommand_from workspace; and test (count (commandline -opc)) -eq 2' -f -a 'reset'
complete -c goobers -n '__fish_seen_subcommand_from blocked; and test (count (commandline -opc)) -eq 2' -f -a 'list clear'
complete -c goobers -n '__fish_seen_subcommand_from claims; and test (count (commandline -opc)) -eq 2' -f -a 'list release'
complete -c goobers -n '__fish_seen_subcommand_from trace; and test (count (commandline -opc)) -eq 2' -f -k -a '(__goobers_completion_runs)'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and test (count (commandline -opc)) -eq 2' -f -a 'verify kill-inject'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and test (count (commandline -opc)) -eq 2' -f -a 'show resolve'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from show; and test (count (commandline -opc)) -eq 3' -f -k -a '(__goobers_completion_escalations)'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve; and test (count (commandline -opc)) -eq 3' -f -k -a '(__goobers_completion_escalations)'
complete -c goobers -n '__fish_seen_subcommand_from completion; and test (count (commandline -opc)) -eq 2' -f -a 'bash zsh fish powershell'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and test (count (commandline -opc)) -eq 2' -f -a 'merges stats errors export prune prune-orphans compact'
complete -c goobers -n '__fish_seen_subcommand_from journal; and test (count (commandline -opc)) -eq 2' -f -a 'redact'
complete -c goobers -n '__fish_seen_subcommand_from help; and test (count (commandline -opc)) -eq 2' -f -a 'all stages instance gaggle goober workflow stage gate harness capability'

complete -c goobers -n '__fish_seen_subcommand_from roots; and __fish_seen_subcommand_from discover' -l json -d 'Emit structured root discovery'
complete -c goobers -n '__fish_seen_subcommand_from roots; and __fish_seen_subcommand_from decommission' -l reason -r -d 'Why this root is historical'
complete -c goobers -n '__fish_seen_subcommand_from version' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from versions' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from init' -l guided -d 'Open browser-based setup'
complete -c goobers -n '__fish_seen_subcommand_from init' -l allow-ephemeral -d 'Allow initialization inside a linked or hosted ephemeral workspace'
complete -c goobers -n '__fish_seen_subcommand_from init' -l instance-path -r -d 'With --guided, instance root to create'
complete -c goobers -n '__fish_seen_subcommand_from init' -l port -r -d 'With --guided, server port or auto'
complete -c goobers -n '__fish_seen_subcommand_from init' -l no-open -d 'With --guided, print the URL without opening a browser'
complete -c goobers -n '__fish_seen_subcommand_from init' -l dev-assets -r -d 'With --guided, serve a local Portal build'
complete -c goobers -n '__fish_seen_subcommand_from init' -l workdir -r -d 'With --guided, temporary browser setup state'
complete -c goobers -n '__fish_seen_subcommand_from init' -l demo -d 'Seed a credential-free runnable demo workflow'
complete -c goobers -n '__fish_seen_subcommand_from init' -l insecure -d 'Allow an unisolated Windows demo'
complete -c goobers -n '__fish_seen_subcommand_from init' -l template -r -a 'quickstart standard' -d 'Seed a named onboarding template'
complete -c goobers -n '__fish_seen_subcommand_from init' -l ci-command -r -d 'With --template=standard, local CI command as JSON argv'
complete -c goobers -n '__fish_seen_subcommand_from init' -l required-capabilities -r -d 'With --template=standard, comma-separated toolchain capabilities'
complete -c goobers -n '__fish_seen_subcommand_from init' -l provider -r -a 'github ado' -d 'With --template=standard, repository provider'
complete -c goobers -n '__fish_seen_subcommand_from init' -l repo -r -d 'With --template=standard, repository identity'
complete -c goobers -n '__fish_seen_subcommand_from init' -l branch -r -d 'With --template=standard, repository branch'
complete -c goobers -n '__fish_seen_subcommand_from init' -l issue-scope -r -a 'all assigned' -d 'With --template=standard, issue selection scope'
complete -c goobers -n '__fish_seen_subcommand_from init' -l assigned-to -r -d 'With --issue-scope=assigned, provider identity'
complete -c goobers -n '__fish_seen_subcommand_from init' -l pr-ci -d 'With --template=standard, use pull-request CI'
complete -c goobers -n '__fish_seen_subcommand_from init' -l workflows -r -d 'With --template=standard, comma-separated workflow modules'
complete -c goobers -n '__fish_seen_subcommand_from init' -l repo-auth-kind -r -a 'azure-cli pat' -d 'With --template=standard, repository authentication kind'
complete -c goobers -n '__fish_seen_subcommand_from init' -l repo-token-env -r -d 'With --template=standard, repository token environment variable'
complete -c goobers -n '__fish_seen_subcommand_from init' -l work-tracking-token-env -r -d 'With --template=standard, work-tracking token environment variable'
complete -c goobers -n '__fish_seen_subcommand_from init' -l pr-token-env -r -d 'With --template=standard, pull-request token environment variable'
complete -c goobers -n '__fish_seen_subcommand_from init' -l push-token-env -r -d 'With --template=standard, repository push token environment variable'
complete -c goobers -n '__fish_seen_subcommand_from init' -l model-token-env -r -d 'With --template=standard, optional model token environment variable'
complete -c goobers -n '__fish_seen_subcommand_from init' -l github-cli-user -r -d 'With --template=standard, authenticated GitHub CLI account'
complete -c goobers -n '__fish_seen_subcommand_from init' -l harness -r -a 'copilot claude-code' -d 'With --template, the harness every seeded goober uses'
complete -c goobers -n '__fish_seen_subcommand_from init' -l source-tree -r -d 'Seed the template as a checked-in config source'
complete -c goobers -n '__fish_seen_subcommand_from init' -l json -d 'Emit the config-source action result as JSON'
complete -c goobers -n '__fish_seen_subcommand_from connect' -l token-env -r -d 'Repository token environment variable name'
complete -c goobers -n '__fish_seen_subcommand_from connect' -l seed -d 'Ensure selector labels and one starter issue on the repository'
complete -c goobers -n '__fish_seen_subcommand_from connect' -l replace -d 'Also rewrite entries already pointing at a real repository'
complete -c goobers -n '__fish_seen_subcommand_from connect' -l json -d 'Emit the versioned onboarding action envelope'
complete -c goobers -n '__fish_seen_subcommand_from preflight' -l distro -r -d 'Select the WSL distro to check'
complete -c goobers -n '__fish_seen_subcommand_from preflight' -l launch-wsl -d 'Run the trailing Goobers command inside WSL'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-sample' -l destination -r -d 'Sample destination'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-sample' -l work-tracking -r -d 'GitHub owner/repo to seed'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-sample' -l token-env -r -d 'Issue token environment variable name'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-sample' -l force -d 'Replace conflicting regular files'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-sample' -l json -d 'Emit the versioned onboarding action envelope'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-agent-instructions' -l source-tree -r -d 'Config source repository root'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-agent-instructions' -l harness -r -a 'copilot claude generic' -d 'Harness adapter'
complete -c goobers -n '__fish_seen_subcommand_from onboarding; and __fish_seen_subcommand_from stub-agent-instructions' -l json -d 'Emit the versioned config-source action envelope'
complete -c goobers -n '__fish_seen_subcommand_from scaffold; and __fish_seen_subcommand_from goober' -l force -d 'Replace generated files that already exist'
complete -c goobers -n '__fish_seen_subcommand_from scaffold; and __fish_seen_subcommand_from workflow' -l force -d 'Replace generated files that already exist'
complete -c goobers -n '__fish_seen_subcommand_from scaffold; and __fish_seen_subcommand_from gaggle' -l force -d 'Replace generated files that already exist (only without --from)'
complete -c goobers -n '__fish_seen_subcommand_from scaffold; and __fish_seen_subcommand_from gaggle' -l from -r -d 'Rename an existing gaggle to <name>'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and __fish_seen_subcommand_from bundle' -l run -r -d 'Limit the bundle to one run id'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and __fish_seen_subcommand_from bundle' -l pr -r -d 'Limit the bundle to runs that touched one pull request'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and __fish_seen_subcommand_from bundle' -l max-runs -r -d 'Maximum runs to collect when no run is named'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and __fish_seen_subcommand_from bundle' -l output -r -d 'Archive path to write'
complete -c goobers -n '__fish_seen_subcommand_from diagnostics; and __fish_seen_subcommand_from bundle' -l json -d 'Write the machine-readable document to stdout'
complete -c goobers -n '__fish_seen_subcommand_from agent-kit; and __fish_seen_subcommand_from install' -l harness -r -a 'copilot claude generic' -d 'Harness adapter'
complete -c goobers -n '__fish_seen_subcommand_from agent-kit; and __fish_seen_subcommand_from update' -l dry-run -d 'Show the update diff without writing'
complete -c goobers -n '__fish_seen_subcommand_from agent-kit; and __fish_seen_subcommand_from update' -l write -d 'Apply product-owned changes'
complete -c goobers -n '__fish_seen_subcommand_from agent-kit; and __fish_seen_subcommand_from update' -l replace-modified -d 'Acknowledge replacement of modified owned files'
complete -c goobers -n '__fish_seen_subcommand_from portal-extension; and __fish_seen_subcommand_from install' -l copilot-home -r -d 'Override the current user\'s Copilot home'
complete -c goobers -n '__fish_seen_subcommand_from portal-extension; and __fish_seen_subcommand_from status' -l copilot-home -r -d 'Override the current user\'s Copilot home'
complete -c goobers -n '__fish_seen_subcommand_from portal-extension; and __fish_seen_subcommand_from update' -l copilot-home -r -d 'Override the current user\'s Copilot home'
complete -c goobers -n '__fish_seen_subcommand_from portal-extension; and __fish_seen_subcommand_from update' -l replace-modified -d 'Replace locally modified extension-owned files'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l json -d 'Emit a versioned findings envelope'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l github-annotations -d 'Emit GitHub Actions file annotations'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l check-harness -d 'Verify referenced agent harnesses are installed and signed in'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l check-repos -d 'Verify target repositories are reachable'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l check-dispatch-namespaces -d 'Verify each gaggle\'s isolation.namespace is dispatch-ready'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l source-tree -d 'Validate a checked-in config source tree'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l instance -r -d 'Real instance document for source-tree placement and capability solving'
complete -c goobers -n '__fish_seen_subcommand_from validate' -l strict -d 'promote config warnings except strict-neutral DVL020, REF012, RNR006, WS001, SAF001, SAF002, SAF003, SAF004, SAF005, SAF006, SAF007 to validation errors'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l json -d 'Emit a versioned findings envelope'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l github-annotations -d 'Emit GitHub Actions file annotations'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l check-harness -d 'Verify referenced agent harnesses are installed and signed in'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l check-repos -d 'Verify target repositories are reachable'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l check-dispatch-namespaces -d 'Verify each gaggle\'s isolation.namespace is dispatch-ready'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l source-tree -d 'Lint a checked-in config source tree'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l instance -r -d 'Real instance document for source-tree placement and capability solving'
complete -c goobers -n '__fish_seen_subcommand_from lint' -l strict -d 'promote config warnings except strict-neutral DVL020, REF012, RNR006, WS001, SAF001, SAF002, SAF003, SAF004, SAF005, SAF006, SAF007 to validation errors'
complete -c goobers -n '__fish_seen_subcommand_from fix' -l to -r -d 'Target DSL version'
complete -c goobers -n '__fish_seen_subcommand_from fix' -l instance-schema -d 'Add the schemaVersion a runners: inventory requires'
complete -c goobers -n '__fish_seen_subcommand_from fix' -l write -d 'Apply migrations in place'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l checks -r -d 'Comma-separated Kubernetes check IDs'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l apiserver-endpoint -r -d 'API-server comparison URL for egress policy drift'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l image-pull-policy -r -a 'always never' -d 'Pull image or explicitly inspect cached artifact only'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l overlay-dir -r -d 'Consumer kustomization directory (--k8s)'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l image-runtime -r -a 'docker podman' -d 'Runtime for pinned image checks'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l image-tools -r -d 'Required PATH tools in pinned images'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l image-ca -r -d 'Internal root CA PEM for image trust checks'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l k8s -d 'Preflight a Kubernetes cluster'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l repo -d 'Compare repository forge policy with GitHub'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l av-exclusions -d 'List the directories Goobers writes then reads and verify antivirus exclusions (advisory)'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l work-root -r -d 'Worker work root to enumerate (--av-exclusions)'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l kubeconfig -r -d 'Kubeconfig path'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l context -r -d 'Kubeconfig context'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l report -r -a 'text json' -d 'Report format'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l oidc-issuer -r -d 'OIDC issuer URL'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l registry -r -d 'Container registry host'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l egress -r -d 'Outbound host and port targets'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l temporal-hostport -r -d 'Temporal frontend host:port'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l temporal-namespace -r -d 'Temporal namespace'
complete -c goobers -n '__fish_seen_subcommand_from doctor' -l timeout -r -d 'Per-probe timeout'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l out -r -d 'Directory to write the rendered manifest set into'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l check -d 'Validate provenance markers, the coverage ratchet, and output freshness'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l baseline -r -d 'Coverage baseline file'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l write-baseline -d 'Freeze the current per-class coverage into the baseline'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l timeout -r -d 'Per-fetch timeout for provenance checks'
complete -c goobers -n '__fish_seen_subcommand_from netpol-render' -l print-blob-endpoint -d 'Print the blob endpoint (namespace, pod labels, port) as JSON and exit'
complete -c goobers -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from diff' -l against -r -d 'Canonical config source root'
complete -c goobers -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from show' -l json -d 'Render the config as JSON instead of YAML'
complete -c goobers -n '__fish_seen_subcommand_from speech; and __fish_seen_subcommand_from preflight' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from speech; and __fish_seen_subcommand_from test' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and __fish_seen_subcommand_from join' -l url -r -d 'Fleet service URL'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and __fish_seen_subcommand_from join' -l enrollment-token-file -r -d 'Private file containing the one-time enrollment grant'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and __fish_seen_subcommand_from join' -l grant-local-admin -d 'Grant the discovered local administrator instance:read'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and __fish_seen_subcommand_from join' -l no-grant-local-admin -d 'Explicitly enroll with an empty ACL'
complete -c goobers -n '__fish_seen_subcommand_from fleet; and __fish_seen_subcommand_from status' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from up' -l quiet -d 'Suppress liveness heartbeats'
complete -c goobers -n '__fish_seen_subcommand_from up' -l diagnostics -d 'Capture deep per-stage diagnostics for hang debugging'
complete -c goobers -n '__fish_seen_subcommand_from up' -l notify -d 'Desktop-notify on escalated/failed runs (=all for every outcome)'
complete -c goobers -n '__fish_seen_subcommand_from up' -l skip-preflight -d 'Start despite config validation errors'
complete -c goobers -n '__fish_seen_subcommand_from up' -l watch-config -d 'Hot-reload materialized config-directory edits (default on; instance.yaml requires restart)'
complete -c goobers -n '__fish_seen_subcommand_from up' -l drain-timeout -r -d 'Force shutdown after this graceful-drain duration'
complete -c goobers -n '__fish_seen_subcommand_from up' -l cleanup-spans-only-runs -d 'Delete reported legacy spans-only run directories at startup'
complete -c goobers -n '__fish_seen_subcommand_from up' -l disable-read-model-reads -d 'Read-model rollback: force authoritative journal scans for this run'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l policy -r -a 'manual on-release on-main' -d 'Update policy'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l include-prerelease -d 'Consider pre-releases when on-release selects the newest target'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l branch -r -d 'Branch tracked by on-main'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l target -r -d 'Manual release tag'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l health-ticks -r -d 'Required clean heartbeat ticks'
complete -c goobers -n '__fish_seen_subcommand_from self-update' -l health-timeout -r -d 'Candidate health window'
complete -c goobers -n '__fish_seen_subcommand_from service; and __fish_seen_subcommand_from install' -l confirm-local-system -d 'Confirm an interactive LocalSystem installation'
complete -c goobers -n '__fish_seen_subcommand_from service; and __fish_seen_subcommand_from install' -l acknowledge-local-system -d 'Acknowledge LocalSystem limitations for non-interactive installation'
complete -c goobers -n '__fish_seen_subcommand_from service; and __fish_seen_subcommand_from status' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from service; and __fish_seen_subcommand_from task-status' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l gaggle -r -d 'Gaggle owning the workflow'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l temporal-hostport -r -d 'Temporal frontend host and port'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l temporal-namespace -r -d 'Temporal namespace'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l task-queue -r -d 'Workflow task queue'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l dedupe-key -r -d 'Run identity deduplication key (requires --direct)'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l direct -d 'Dispatch straight to Temporal instead of through the running daemon'
complete -c goobers -n '__fish_seen_subcommand_from engine-start' -l live-journal -d 'Author the run journal live through the daemon\'s journal plane'
complete -c goobers -n '__fish_seen_subcommand_from engine-queues' -l temporal-hostport -r -d 'Temporal frontend host and port'
complete -c goobers -n '__fish_seen_subcommand_from engine-queues' -l temporal-namespace -r -d 'Temporal namespace'
complete -c goobers -n '__fish_seen_subcommand_from engine-queues' -l task-queue -r -d 'Workflow task queue'
complete -c goobers -n '__fish_seen_subcommand_from engine-queues' -l timeout -r -d 'Bound on the whole describe'
complete -c goobers -n '__fish_seen_subcommand_from engine-queues' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from engine-project' -l gaggle -r -d 'Gaggle owning the run'
complete -c goobers -n '__fish_seen_subcommand_from engine-project' -l temporal-hostport -r -d 'Temporal frontend host and port'
complete -c goobers -n '__fish_seen_subcommand_from engine-project' -l temporal-namespace -r -d 'Temporal namespace'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l instance -r -d 'Instance root; wires the real executors'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l blob-store -r -d 'Directory backing the fleet artifact store'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l daemon-api -r -d 'Daemon write API base URL for live journal emission'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l dispatch-namespace -r -d 'Namespace for mode-3 stage pods; wires the dispatcher seam'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l config-reload-interval -r -d 'How often to re-read the instance config tree and rebuild changed gaggle seams (0 disables)'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l config-history-depth -r -d 'How many superseded config trees to retain so an in-flight run pinned to one is still served its own goober kit (0 disables)'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l task-queue -r -d 'Task queue to serve (repeatable)'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l temporal-hostport -r -d 'Temporal frontend host and port'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l temporal-namespace -r -d 'Temporal namespace'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l drain-timeout -r -d 'Graceful-drain timeout'
complete -c goobers -n '__fish_seen_subcommand_from worker' -l work-root -r -d 'Stage workspace root'
complete -c goobers -n '__fish_seen_subcommand_from config-seed' -l mirror -r -d 'Read-only rendered config mirror path'
complete -c goobers -n '__fish_seen_subcommand_from config-seed' -l instance -r -d 'Private worker instance path'
complete -c goobers -n '__fish_seen_subcommand_from dashboard' -l port -r -d 'Dashboard port, or auto'
complete -c goobers -n '__fish_seen_subcommand_from dashboard' -l listen -r -d 'Bind address as host:port; non-loopback requires api.auth'
complete -c goobers -n '__fish_seen_subcommand_from dashboard' -l no-open -d 'Print the URL without opening a browser'
complete -c goobers -n '__fish_seen_subcommand_from dashboard' -l dev-assets -r -d 'Serve a local portal build'
complete -c goobers -n '__fish_seen_subcommand_from dashboard' -l wait-for-daemon -d 'Wait up to 30s for a concurrently starting daemon'
complete -c goobers -n '__fish_seen_subcommand_from run' -l no-api -d 'Explicitly use local execution or file delegation'
complete -c goobers -n '__fish_seen_subcommand_from run' -l api-timeout -r -d 'Bound API validation and acceptance'
complete -c goobers -n '__fish_seen_subcommand_from run' -l force -d 'Bypass hourly and daily cadence budgets for this manual run'
complete -c goobers -n '__fish_seen_subcommand_from run' -l gaggle -r -d 'Trigger the workflow in this gaggle'
complete -c goobers -n '__fish_seen_subcommand_from run' -l github-progress -d 'Publish live progress to one GitHub Check Run'
complete -c goobers -n '__fish_seen_subcommand_from run' -l pr -r -d 'Target an exact pull request for merge-review'
complete -c goobers -n '__fish_seen_subcommand_from run' -l api -r -d 'Daemon API base URL for a remote daemon'
complete -c goobers -n '__fish_seen_subcommand_from run' -l request-id -r -d 'Retry-safe delivery identity for an API submission'
complete -c goobers -n '__fish_seen_subcommand_from run' -l no-wait -d 'Return on durable API acceptance or local dispatch'
complete -c goobers -n '__fish_seen_subcommand_from approve' -l decision -r -d 'Gate decision'
complete -c goobers -n '__fish_seen_subcommand_from approve' -l actor -r -d 'Recorded actor identity'
complete -c goobers -n '__fish_seen_subcommand_from approve' -l api -r -d 'Daemon API base URL for a remote daemon'
complete -c goobers -n '__fish_seen_subcommand_from override' -l rationale -r -d 'Override rationale'
complete -c goobers -n '__fish_seen_subcommand_from override' -l decision -r -d 'Gate decision'
complete -c goobers -n '__fish_seen_subcommand_from override' -l actor -r -d 'Recorded actor identity'
complete -c goobers -n '__fish_seen_subcommand_from override' -l api -r -d 'Daemon API base URL for a remote daemon'
complete -c goobers -n '__fish_seen_subcommand_from rerun-stage' -l addendum -r -d 'Instruction addendum'
complete -c goobers -n '__fish_seen_subcommand_from rerun-stage' -l actor -r -d 'Recorded actor identity'
complete -c goobers -n '__fish_seen_subcommand_from rerun-stage' -l api -r -d 'Daemon API base URL for a remote daemon'
complete -c goobers -n '__fish_seen_subcommand_from workflow; and __fish_seen_subcommand_from show' -l dot -d 'Emit Graphviz DOT'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from list' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from list' -l phase -r -d 'Filter by phase'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from list' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Filter by workflow'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from list' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from list' -l limit -r -d 'Maximum runs'
complete -c goobers -n '__fish_seen_subcommand_from runs; and __fish_seen_subcommand_from du' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from status' -l agents -d 'List in-flight agentic stages by role'
complete -c goobers -n '__fish_seen_subcommand_from status' -l all -d 'Show individual detail for manual-only workflows'
complete -c goobers -n '__fish_seen_subcommand_from status' -l daemon -d 'Report daemon health and identity'
complete -c goobers -n '__fish_seen_subcommand_from status' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from status' -l phase -r -d 'Filter by phase'
complete -c goobers -n '__fish_seen_subcommand_from status' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Filter by workflow'
complete -c goobers -n '__fish_seen_subcommand_from status' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from status' -l limit -r -d 'Maximum runs'
complete -c goobers -n '__fish_seen_subcommand_from status' -l watch -d 'Refresh the status board until interrupted'
complete -c goobers -n '__fish_seen_subcommand_from status' -l interval -r -d 'Watch refresh interval'
complete -c goobers -n '__fish_seen_subcommand_from stats' -l since -r -d 'Only include activity from the preceding duration'
complete -c goobers -n '__fish_seen_subcommand_from stats' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l pr -r -d 'Filter to one pull request'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l issue -r -d 'Filter to one issue'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l provider -r -a 'github ado' -d 'Filter external-reference provider'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l window -r -d 'Bounded lookback duration'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l since -r -d 'Inclusive RFC3339 run-start lower bound'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l until -r -d 'Exclusive RFC3339 run-start upper bound'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from cost' -l rebuild -d 'Rebuild telemetry before querying'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l provider -r -d 'Filter by provider'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l repository -r -d 'Filter by repository'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l kind -r -a 'pr issue' -d 'Filter by work-item kind'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l id -r -d 'Show one work item\'s action timeline'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l limit -r -d 'Maximum work items'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from work-items' -l rebuild -d 'Rebuild telemetry from run journals before querying'
complete -c goobers -n '__fish_seen_subcommand_from features' -l json -d 'Emit a versioned feature-discovery envelope'
complete -c goobers -n '__fish_seen_subcommand_from features' -l dsl-version -r -d 'Scope features to one DSL version'
complete -c goobers -n '__fish_seen_subcommand_from features' -l used -d 'List only features referenced by the instance'
complete -c goobers -n '__fish_seen_subcommand_from schema' -l list -d 'List every embedded schema kind'
complete -c goobers -n '__fish_seen_subcommand_from schema' -l human -d 'Emit a human-readable rendering'
complete -c goobers -n '__fish_seen_subcommand_from queue-explain' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from queue-explain' -l pr -r -d 'PR number to explain'
complete -c goobers -n '__fish_seen_subcommand_from queue-explain' -l gaggle -r -d 'Gaggle namespace'
complete -c goobers -n '__fish_seen_subcommand_from queue-explain' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Workflow that evaluated the queue'
complete -c goobers -n '__fish_seen_subcommand_from explain' -l human -d 'Emit a human-readable rendering'
complete -c goobers -n '__fish_seen_subcommand_from recovery-abandon' -l run -r -d 'Terminal source run'
complete -c goobers -n '__fish_seen_subcommand_from recovery-abandon' -l ref -r -d 'Exact recovery ref'
complete -c goobers -n '__fish_seen_subcommand_from recovery-abandon' -l confirm-digest -r -d 'Confirm published patch digest'
complete -c goobers -n '__fish_seen_subcommand_from recovery-restore' -l record -r -d 'Published recovery record'
complete -c goobers -n '__fish_seen_subcommand_from recovery-restore' -l issue -r -d 'Issue with retained implementation'
complete -c goobers -n '__fish_seen_subcommand_from recovery-restore' -l repository-key -r -d 'Canonical repository key'
complete -c goobers -n '__fish_seen_subcommand_from recovery-restore' -l repository -r -d 'Destination Git repository'
complete -c goobers -n '__fish_seen_subcommand_from recovery-restore' -l branch -r -d 'New local operator branch'
complete -c goobers -n '__fish_seen_subcommand_from blocked; and __fish_seen_subcommand_from list' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from list' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from list' -l stale -d 'Show only expired claims'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from list' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from list' -l provider -r -d 'Filter by provider'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from release' -l gaggle -r -d 'Gaggle owning the claim'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from release' -l provider -r -d 'Provider owning the claim'
complete -c goobers -n '__fish_seen_subcommand_from claims; and __fish_seen_subcommand_from release' -l force -d 'Release a claim held by a non-terminal run'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l follow -d 'Stream events until the run reaches a terminal phase'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l summary -d 'Show run metadata and review verdicts'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l verdicts -d 'Show review verdict content'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l transcripts -d 'Show every recorded agent-stage transcript'
complete -c goobers -n '__fish_seen_subcommand_from trace' -l transcript -r -d 'Show recorded transcript data for one stage'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from verify' -l run -r -a '(__goobers_completion_runs)' -d 'Run id to verify'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from verify' -l gaggle -r -d 'Require the run belong to this gaggle'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from verify' -l expected -r -d 'Topology expectations JSON file'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from verify' -l out -r -d 'Write the evidence bundle here instead of stdout'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from verify' -l print-runner-class -r -d 'Print the runner-class label value for a restriction set and exit'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l run -r -a '(__goobers_completion_runs)' -d 'Run id whose stage attempt to kill'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l stage -r -d 'The real workflow stage name to target'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l stage-class -r -d 'Which S6 stage class this stage plays: builtin, agentic, or local-ci'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l namespace -r -d 'Kubernetes namespace the target pod runs in'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l poll-timeout -r -d 'Bound on each polling phase'
complete -c goobers -n '__fish_seen_subcommand_from e2e; and __fish_seen_subcommand_from kill-inject' -l out -r -d 'Write the injection record here instead of stdout'
complete -c goobers -n '__fish_seen_subcommand_from escalations' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from show' -l include-verdict -d 'Include review verdict content'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l resolution -r -a 'approve deny redirect' -d 'Escalation resolution'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l gate -r -d 'Escalated gate for approve and redirect'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l decision -r -d 'Branch decision for redirect'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l rationale -r -d 'Audit rationale'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l actor -r -d 'Recorded actor identity'
complete -c goobers -n '__fish_seen_subcommand_from escalations; and __fish_seen_subcommand_from resolve' -l api -r -d 'Daemon API base URL for a remote daemon'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l compare-github -r -d 'Compare an explicit GitHub owner/repository'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l shared-identities -r -d 'Comma-separated shared merger logins'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l instance-id -r -d 'Filter by originating instance'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l repository-api-url -r -d 'Filter by repository API address'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l since -r -d 'Inclusive start timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l until -r -d 'Exclusive end timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from merges' -l rebuild -d 'Rebuild from retained journals'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Filter by workflow'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l branch -r -d 'Filter by journal branch'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l model -r -d 'Filter by model'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l harness-version -r -d 'Filter by harness version'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l group-by -r -d 'Group by model or harness-version'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l since -r -d 'Include runs at or after this RFC3339 timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l until -r -d 'Include runs at or before this RFC3339 timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from stats' -l rebuild -d 'Rebuild telemetry from run journals before querying'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l json -d 'Emit JSON'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Filter by workflow'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l gaggle -r -d 'Filter by gaggle'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l class -r -d 'Filter by error class'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l limit -r -d 'Maximum errors'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l since -r -d 'Include errors at or after this RFC3339 timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l until -r -d 'Include errors at or before this RFC3339 timestamp'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from errors' -l rebuild -d 'Rebuild telemetry from run journals before querying'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from export' -l since -r -d 'Inclusive span-start lower bound'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from export' -l until -r -d 'Exclusive span-start upper bound'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from prune' -l dry-run -d 'Report eligible runs without deleting them'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from prune-orphans' -l delete -d 'Delete eligible orphan directories (opt-in; default dry-run)'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from prune-orphans' -l min-age -r -d 'Minimum inactivity age (at least 24h)'
complete -c goobers -n '__fish_seen_subcommand_from telemetry; and __fish_seen_subcommand_from compact' -l dry-run -d 'Report reclaimable data without changing it'
complete -c goobers -n '__fish_seen_subcommand_from journal; and __fish_seen_subcommand_from redact' -l run -r -a '(__goobers_completion_runs)' -d 'Run id'
complete -c goobers -n '__fish_seen_subcommand_from journal; and __fish_seen_subcommand_from redact' -l path -r -d 'Journal-relative blob path'
complete -c goobers -n '__fish_seen_subcommand_from journal; and __fish_seen_subcommand_from redact' -l reason -r -d 'Redaction reason'
complete -c goobers -n '__fish_seen_subcommand_from journal; and __fish_seen_subcommand_from redact' -l secret-file -r -d 'Read the leaked secret bytes from this file'
complete -c goobers -n '__fish_seen_subcommand_from backlog-health' -l feedback -d 'Include backlog feedback'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l claim -d 'Claim the first eligible item'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l resweep -d 'Run scheduled re-sweep with --claim'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l debug -d 'Explain candidate eligibility and exclusions'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l release -d 'Release this run\'s claim leases early'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l read-only -d 'Query without mutating provider state'
complete -c goobers -n '__fish_seen_subcommand_from backlog-query' -l reconcile -d 'Reconcile claim state'
complete -c goobers -n '__fish_seen_subcommand_from file-issues' -l check -d 'Validate and scan without creating issues'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-branches' -l delete -d 'Delete eligible branches (opt-in; default dry-run)'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-branches' -l max -r -d 'Maximum candidates inspected in one sweep'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-branches' -l min-age -r -d 'Minimum terminal run age required for deletion'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-branches' -l after -r -d 'Resume after this branch name in lexical order'
complete -c goobers -n '__fish_seen_subcommand_from set-milestone' -l item -r -d 'Issue item id'
complete -c goobers -n '__fish_seen_subcommand_from set-milestone' -l milestone -r -d 'Milestone number'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-post-merge' -l max -r -d 'Maximum pull requests to reconcile'
complete -c goobers -n '__fish_seen_subcommand_from reconcile-post-merge' -l lookback -r -d 'Merge lookback duration'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l source -r -a 'code-scanning dependabot' -d 'Alert feed to read'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l state -r -a 'open dismissed fixed auto_dismissed all' -d 'Alert state filter (default open)'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l severity -r -d 'Comma-separated severity filter'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l tool -r -d 'Code-scanning analysis tool name'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l ref -r -d 'Code-scanning git ref'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l ecosystem -r -d 'Comma-separated Dependabot package ecosystems'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l scope -r -a 'runtime development' -d 'Dependabot dependency scope'
complete -c goobers -n '__fish_seen_subcommand_from security-alerts-query' -l max-results -r -d 'Maximum alerts to collect'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l window -r -d 'Lookback window (e.g. 24h)'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l aggregate -r -a 'all stage-failure-rate error-signature ci-check-failure gate-noise workflow-untriggered stage-unreached credit-assignment learning-episode' -d 'Aggregate to detect'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l learning-action -r -a 'instruction-or-skill workflow-or-gate targeted-test-mapping code-issue' -d 'Governed learning action to include'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l threshold -r -d 'Threshold override k=v'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l format -r -a 'candidate-findings effective-version-efficacy tutor-live-verification' -d 'Artifact format'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l gaggle -r -d 'Gaggle to query'
complete -c goobers -n '__fish_seen_subcommand_from telemetry-query' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Workflow keying the query'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l repo -r -d 'Git repository/worktree to scan'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l workflow -r -a '(__goobers_completion_workflows)' -d 'Workflow keying the watermark'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l gaggle -r -d 'Gaggle keying the watermark'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l since -r -d 'First-run window and minimum buffer floor'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l buffer-multiplier -r -d 'Buffer multiplier over observed churn'
complete -c goobers -n '__fish_seen_subcommand_from docs-churn' -l format -r -a 'churn-digest' -d 'Artifact format'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l project -r -d 'Xcode project path'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l workspace -r -d 'Xcode workspace path'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l scheme -r -d 'Xcode scheme'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l device -r -d 'Simulator device'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l runtime -r -d 'Simulator runtime'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l only-testing -r -d 'Test target filter'
complete -c goobers -n '__fish_seen_subcommand_from ios-simulator-test' -l result-bundle -r -d 'Result bundle path'
complete -c goobers -n '__fish_seen_subcommand_from gather-sibling-context' -l no-cache -d 'Bypass the sibling-context cache'
complete -c goobers -n '__fish_seen_subcommand_from gather-sibling-context' -l no-verdict-cache -d 'Skip the verdict-cache lookup, forcing a fresh review'
complete -c goobers -n '__fish_seen_subcommand_from apply-verdict' -l gate -r -d 'Gate name whose verdict to apply'
complete -c goobers -n '__fish_seen_subcommand_from elect-lander' -l gate -r -d 'Gate name whose verdict to read'
complete -c goobers -n '__fish_seen_subcommand_from pr-claim' -l release -d 'Release the remediation claim'
complete -c goobers -n '__fish_seen_subcommand_from remediation-checkpoint' -l budget -r -d 'Per-PR repass-cycle budget before escalating'
complete -c goobers -n '__fish_seen_subcommand_from remediation-checkpoint' -l escalate -r -d 'Escalate unconditionally with this reason'
complete -c goobers -n '__fish_seen_subcommand_from remediation-checkpoint' -l escalation-outcome -r -d 'Recorded escalation outcome'
complete -c goobers -n '__fish_seen_subcommand_from respond-to-findings' -l check -d 'Validate without publishing responses'
complete -c goobers -n '__fish_seen_subcommand_from mcp-io' -l config -r -d 'MCP server configuration path'
